### ISSUE TITLE
Double listing

### ISSUE THREAD

**Issue by OOMMPA** [danvratil/FBEventSync#17]
All events are listed twice on my calendar.  Birthdays once, but ALL other events twice.

**Comment by KTorski** [comment]
I'm having the same problem

**Comment by Ezarra** [comment]
I'm having the same problem, as well

**Comment by danvratil** [comment]
Hopefully, the duplication of events during sync was fixed in commit 3ba74534a (which rolled over the weekend). You may need to recreate the app account to make all the duplicates go away first.

Feel free to reopen the issue if you get duplicate events even with version 0.16 (or newer).
