### ISSUE TITLE
Make reminder times for all-day events customizable

### ISSUE THREAD

**Issue by Maritaav** [danvratil/FBEventSync#25]
How do I avoid sounds every night (midnight) when my FB friends have a birthday?

**Comment by danvratil** [comment]
You can disable birthday notifications in the app in Calendar Settings -> Friends' Birthdays -> Reminders.

I'll look into shifting the birthday and all-day events reminders to some more reasonable hours :)

**Comment by Maritaav** [comment]
If I do that, will I not lose all the birthday reminders?? I only want the sound to go away

**Comment by danvratil** [comment]
Indeed, disabling reminders in the app will remove the reminders from the events (so you won't be reminded at all).

Event notification appearance and sounds are not in control of the app, you should look into your Calendar app settings or your Settings app if you can change the notification sounds there (or maybe if there's some "Quiet hours" option).

**Comment by Maritaav** [comment]
Can't find anything there

**Comment by danvratil** [comment]
Then you will have to disable the reminders for now and I'll look into having the birthday reminder times customizable. Birthdays are all-day events thus they start at midnight, so the notifications are technically correct but practically pointless.

I'll try to look into this soon.

**Comment by Maritaav** [comment]
Thank you for your help so far.
