### ISSUE TITLE
Two Factors Authentication on Facebook

### ISSUE THREAD

**Issue by Benbb96** [danvratil/FBEventSync#29]
I changed my password on Facebook ans add a two factors authentication so that I receive an SMS to login.
Since I didn't see my events on my calendar like before. I installed again the app to be able to reconnect Facebook, but it seems that it is not possible to authenticate with two factors : "_Failed to retrieve calendar URI_". I can see the text input to enter the code but the page automatically disappears..

**Comment by Benbb96** [comment]
It's ok, I received a notification 20 minutes later to authorize the app to connect and it's now working. It also kept my configuration!

That's a really nice work, thank you @danvratil 😉

**Comment by danvratil** [comment]
This is partly related to #28 (no login prompt when existing auth session become invalid, like when you change your password or toggle 2FA) and #18 (no way to fully log out from Facebook without re-installing the app).

Sounds like the app wrongly detected the 2FA page as an authentication error, I'll look into that.

**Comment by danvratil** [comment]
Turns out I broke 2FA handling in the previous update. Version 0.25 will start rolling out soon with 2FA flow fixed.
