### ISSUE TITLE
Shared Calendars and Confirmed Events

### ISSUE THREAD

**Issue by rnc** [danvratil/FBEventSync#37]
This is not a bug but a potential design/enhancement discussion :-)

So, myself and my wife share our calendars. If I've flagged an event as something we're going to it doesn't appear in my personal calendar on the web interface on my computer which means her share of my calendar does not see it. Which leads to double booking ;-)

So while the application works perfectly on a single phone I'm wondering whether there could be a way to persist certain categories (e.g. Events Going To, Events Interested In) into a specified calander therebye allowing cross-device usage/syncing.

**Comment by danvratil** [comment]
I assume you share a Google Calendar? This app does not sync into a Google Calendar, it creates the few calendars only locally in the device, therefore you don't see anything in your Google Calendars on the web, but check this [FAQ](https://github.com/danvratil/FBEventSync/wiki/FAQ#how-do-i-sync-facebook-events-into-google-calendar) .
