### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [danvratil/FBEventSync#43]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by danvratil** [comment]
Hi,

thanks for the suggestion, having the app on F-Droid would be great! No promise on when I'll have time to check out the inclusion guide and go through the process, so feel free (or anyone else) to go ahead with it. I'll be more than happy to assist if something needs to be fixed or changed in the app to be accepted by F-Droid, just let me know here or open a new ticket.

**Comment by Poussinou** [comment]
I opened a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/652). Our bot will scan your source code, and somebody will probably take care of this.

**Comment by licaon-kter** [comment]
@danvratil 
The issues that I see:
* you tag betas (with the same pattern) too, making F-Droid pull them as stable
* you named releases as `0.26 (beta X)` but the actual versionName was just `0.26`
* then given the versionName above, you can't separate betas from stable
* also you can't separate `beta 1` from `beta 2` since you named them both `0.26`
* F-Droid updater would error out as the versionName would be the same but for a different versionCode

**Comment by danvratil** [comment]
@licaon-kter thanks for the feedback. The current schema indeed is a mess :) 

So, should I not git tag betas at all, or should I use an explicit pattern like `0.26-beta1`, `0.26-beta2` etc. that can be excluded in some F-Droid rules?

Regarding the version names, I'll unify them across git tags, versionName and Github Releases, adopting the `0.26` (`major.minor`) schema.

If this is OK, I'll do a new release tonight adopting the new schema.

**Comment by licaon-kter** [comment]
> should I use an explicit pattern like 0.26-beta1, 0.26-beta2 

Yes please, you can delete & retag

> Regarding the version names

As you wish, but never use the same, beta1 is 26, beta2 should be 27, release would be 28, so on...
