### ISSUE TITLE
Still getting duplicate events!

### ISSUE THREAD

**Issue by Cloudchowder** [danvratil/FBEventSync#45]
I've had to uninstall for now, because I can't have 20, 30, or 50 duplicates of the same event cluttering my calendar. It isn't just all-day events; this is happening with all different events no matter their duration. It's even persisting after I go back into Facebook and decline an event in an effort to stop it duplicating things. I have "events I've declined" set to NOT show in my calendar, but the same duplicate events are still there despite declining and resyncing. Like many people, I pretty much depend on Facebook events for my calendar and don't want to go back to having to manually enter them, so please make fixing this a priority.

**Comment by Drakone** [comment]
Same problem :/.

**Comment by Cloudchowder** [comment]
I reinstalled to see how it would behave again, and it seems to have chosen one particular event to duplicate. It duplicated the event a couple of times, so I uninstalled to get rid of those entries. Reinstalled, and as of 8 hours ago there was only one instance of the event. This morning there are eight instances. Just this one event. I'll have to decline it (again, though I am attending) on Facebook, then uninstall and reinstall Event Sync to clear these entries from my calendar.

I AM TIRED OF THIS.

**Comment by Cloudchowder** [comment]
UPDATE: I think I've figured out part of this. What it seems to be doing is taking the most immediate one or two events (something happening today or tomorrow, occasionally something that happened yesterday) and duplicating those. Even if I have declined the event on Facebook, then uninstalled and reinstalled Event Sync... it still gets pulled in and duplicated, then shown as an event I am attending or did attend.

**Comment by guyweiss** [comment]
Same problem. I think it duplicates everytime the app get synced for ongoing events. For example an event ongoing is 4 hours than it will be duplicated 4 times (i choose to sync once an hour). Hope this bug will be fixed. I sent the author a few times to reply for this issue

**Comment by danvratil** [comment]
0.28 update with the fix is rolling out into Play Store right now.
