### ISSUE TITLE
Add-on for Thunderbird

### ISSUE THREAD

**Issue by PanderMusubi** [danvratil/FBEventSync#52]
Please, consider making also an add-on for Thunderbird with the same functionality as this app. See https://addons.thunderbird.net/en-US/thunderbird/ and for example code see https://addons.thunderbird.net/en-US/seamonkey/addon/thunderbirthday/

**Comment by danvratil** [comment]
Sorry, I don't use Thunderbird, so I have no interest (or time, sadly) to develop for it. If you are using Linux, I wrote a Facebook event sync for Kontact (although I need to find some time to fix it again to work with the latest FB changes).

**Comment by PanderMusubi** [comment]
Thanks for elaborating. Perhaps add in the README here a link to the sync for Kontact and a motivational hint that someone develops a Thunderbird add-on. ;-)
