### ISSUE TITLE
I keep getting timeout when trying to retrieve events.

### ISSUE THREAD

**Issue by HarryHeights** [danvratil/FBEventSync#61]
I'm unable to use the software. It keeps telling me failed to retrieve calendar export link.

By the way, I checked out your privacy policy statement. It could better with a little more formal composition.
I could create that for you, if you don't mind.

**Comment by danvratil** [comment]
Hi,

weird, probably something is not loading correctly :(

Help with the Privacy Policy is much welcomed, I've just thrown something together because I had to, I don't have much clue about the legal wordings or what not :)

**Comment by HarryHeights** [comment]
Privacy Policy done. I hope you work a fix quickly about this issue. I desperately need an app like this. Especially for remembering birthdays. I've received some stick lately from my friends for not remembering their birthdays. This would solve that problem for me. Thanks

**Comment by danvratil** [comment]
Thanks again for writing the policy!

Could you check the sync logs, see what exactly it says about the export link retrieval?

**Comment by HarryHeights** [comment]
You are welcome!

Where can I check the sync logs?.

**Comment by danvratil** [comment]
In the app, in the side-bar, there should be an option called "sync logs".

**Comment by HarryHeights** [comment]
![Screenshot_2019-03-13-11-38-09-114_cz dvratil fbeventsync](https://user-images.githubusercontent.com/40593824/54272743-9045bd80-4584-11e9-8257-870eb668ff71.png)


That's a screenshot of the logs.

**Comment by danvratil** [comment]
Thanks, this helped - I do have a fix for this problem, just needs a new release.

**Comment by HarryHeights** [comment]
Okay great. With this release be coming out soon? I need this app desperately. 😁😁

**Comment by danvratil** [comment]
There's one more bug that I'd like to take a look at, but generally, I can roll it out tonight when I get home from work :)

**Comment by HarryHeights** [comment]
Great. Thanks.

**Comment by danvratil** [comment]
Update 0.36 with a fix will start rolling out soon. Let me know if there are still any issues :)

**Comment by HarryHeights** [comment]
Alright. Will do. Thanks
