### ISSUE TITLE
Login Facebook 

### ISSUE THREAD

**Issue by Aleve1983** [danvratil/FBEventSync#70]
No log in Facebook

**Comment by tokenmath** [comment]
Yes yes

**Comment by mxmilkb** [comment]
I've upgraded to a Note 9. Now I get the message: "Login Failed: You can't use Facebook to log into this app or website because there's an issue with its implementation of Facebook Login."

**Comment by damionx7** [comment]
Developers please respond. Could it be because of 2fa

**Comment by fear-the-beaver** [comment]
Same issue on op5t oos 9.0.10 with enabled 2fa on facebook. 
![Screenshot_20200124-092116](https://user-images.githubusercontent.com/46751130/73076231-b79b3580-3e8b-11ea-83c9-ea8ef9ef205b.jpg)

**Comment by danvratil** [comment]
This should be fixed by now.
