### ISSUE TITLE
[FR] Distinct calender for saved events

### ISSUE THREAD

**Issue by ChristianTacke** [danvratil/FBEventSync#72]
FB allows to mark events as "saved".
This seems to work on normal an on recurring events.

Currently, they're in the "maybe" calender. That's okay, because that's close enough.

Having a distinct calender might be a nice addition.

Is this possible at all?

**Comment by danvratil** [comment]
Sadly, this is not possible. This information is not provided by Facebook, we would have to scrape the actual event website, which is not really allowed and fairly difficult to do...
