### ISSUE TITLE
Never finishes calendar sync

### ISSUE THREAD

**Issue by cj5neal** [danvratil/FBEventSync#80]
Latest update. Retrieves account and such but gets yo sync calendar and basically get the old spinning wheel of death. Nothing happens.

**Comment by cj5neal** [comment]
![Screenshot_20200612-135732](https://user-images.githubusercontent.com/66842732/84532731-bb055100-acb4-11ea-8619-e3fe27f59481.jpg)

**Comment by danvratil** [comment]
Could you try removing the account from the app completely and adding it from scratch? Is there anything suspicious in logs?

**Comment by cj5neal** [comment]
I tried removing the account. Same problem. I deleted the app. Same
problem....i am a beta tester if it makes a difference.

**Comment by realgrm** [comment]
Same thing here. OnePlus 7 Android 10

**Comment by cj5neal** [comment]
OnePlus 7pro is my device

**Comment by tomasz245** [comment]
me too, same problem on Nexus 5x

**Comment by emkael** [comment]
Have you got the new/beta Facebook design turned on by chance? I've reverted to the "old" layout and the sync started to work once again.

**Comment by cj5neal** [comment]
I do not see any option for layout in the app and do not see any difference
in my layout

**Comment by emkael** [comment]
It's a Facebook option, global for an account, available since they've started rolling out the new design. "Switch to New Facebook"/"Switch to Classic Facebook" in the main account menu on FB website.

**Comment by cj5neal** [comment]
Ahha....i will check it out and see if that is the issue

**Comment by emkael** [comment]
FYI: I'm not entirely sure that's the main cause of the problems, as now I've switched back to "New" and sync still seems to be working (at least according to the logs), but maybe it's something on the first run that prevented the inital sync.

**Comment by cj5neal** [comment]
The sync completed now but I do not see the birthdays in calendar....ugh

**Comment by cj5neal** [comment]
Yeah it syncs but birthdays and events do not appear on my calendar

**Comment by danvratil** [comment]
Birthdays do not work as of now, Facebook no longer publishes them. I am not sure I'll be able to find another way around to get birthdays. Weird that events do not show up as well, anything in the logs?

Regarding the classic vs. new, the classic theme is indeed required for the first sync after login, as only there we can find the link to the iCal event file that's used as a source for the events. Afterwards it doesn't matter anymore which Facebook theme you use.

**Comment by GammaRay360** [comment]
Still doesn't work for me. stuck on "Retrieving calendars". I tried a few times from scratch

**Comment by airon90** [comment]
I just installed this app and this doesn't work for me too, so it is not a problem about login/account

**Comment by simbalasim** [comment]
After I changed my FB password I have the same problem. I deactivated 2fa for testing, no luck. And it's not possible anymore to switch to the classic fb theme. So this workaround can't be used.

**Comment by danvratil** [comment]
Facebook has completely removed support for the "Old UI" some time ago and so was gone the way to retrieve the calendars. It's back now (maybe has been back for a while, I mostly gave up on the app  after the UI update). I should be able to solve that in next update - details in #85
