### ISSUE TITLE
Authentication expires, no sync possible

### ISSUE THREAD

**Issue by MaluNoPeleke** [danvratil/FBEventSync#82]
Whenever I try to sync my Facebook events with the app I have to reauthenticate again and again but no sync is finalizing.
This is the error:

> Response indicates expired iCal URI, offering reauthentication

**Comment by ckkoen** [comment]
Yep, I'm seeing the exact same problem here.

**Comment by danvratil** [comment]
Facebook has completely removed support for the "Old UI" some time ago and so was gone the way to retrieve the calendars again if the authentication expired. It's back now (maybe has been back for a while, I mostly gave up on the app  after the UI update). I should be able to solve that in next update - details in #85
