### ISSUE TITLE
Never retrieves calendar

### ISSUE THREAD

**Issue by hvaffornoget** [danvratil/FBEventSync#84]
Mine is just stuck on 'retrieving calendars' until it eventually just stops with no signs, or I forget to keep the screen lit and it has just given up when I touch the phone again. Hasn't done one successful sync. 
![Screenshot_20200905_190640_cz dvratil fbeventsync](https://user-images.githubusercontent.com/4385224/92310082-2fe1e180-efab-11ea-9f7e-70b3fb838e78.jpg)

**Comment by danvratil** [comment]
Facebook has completely removed support for the "Old UI" some time ago and so was gone the way to retrieve the calendars. It's back now (maybe has been back for a while, I mostly gave up on the app  after the UI update). I should be able to solve that in next update - details in #85
