### ISSUE TITLE
News FB design and no calendar retrieve.

### ISSUE THREAD

**Issue by SupaOz** [danvratil/FBEventSync#85]
Hello,
From now on, the new FACEBOOK design can no longer be demoted. For those who had already synchronized by reverting to the old design, this continues to work. My example, my Nokia 6.1 continues to sync.
The problem is with new users. Yesterday I changed my phone and arrived under a pixel 3a.
I can't downgrade facebook design now, so I can't do a first sync with FBEventSync.
Did someone find a solution, or could the developer tell us about the progress of this bug? is it identified by it, being tested / resolved?

Thanks in advance for the information.

**Comment by danvratil** [comment]
As far as I can see this may very well be the end. It's now only possible to export a single event to iCal, but there no longer seems to be any way how to get list of user's events, sorry.

**Comment by SupaOz** [comment]
Thank you for this feedback.

Do you think there is a way to hope for the future? Because if we can no longer synchronize events, Facebook loses 50% of its usefulness. finally from my point of view, I mainly use FB for the sync of concerts and evening in the bars of my city.

**Comment by Perdellian** [comment]
It can only handle one event page at a time, but this at least something you can share a URL to:

NoFb Event Scraper (Import Facebook-Events to the calendar) - https://f-droid.org/packages/com.akdev.nofbeventscraper

Combined with an app wrapper like [Frost](https://allanwang.github.io/Frost-for-Facebook/), this lets me get more of the Facebook experience relatively smoothly without relying on the official app. (I'm still waiting for Frost's messenger support to improve past beta so I can ditch the official app for that, but beggars and choosers, y'know?)

It's nowhere near as smooth as automatic sync, of course, but it's at least something that can (relatively) easily be added to the workflow of responding to an event in the first place.

**Comment by danvratil** [comment]
Never mind, there actually is a way to get to the link with all events again \o/ Fixing the app should be trivial, let me see if I can roll out something during the week...

**Comment by danvratil** [comment]
Version 0.46 is rolling out to production on Play Store. Let me know if there are any issues with the sync.
